GET http://localhost:3000/bank-accounts

###

GET http://localhost:3000/bank-accounts/eb6cebee-5e7d-4b5d-b766-07d94b282abf

###

POST http://localhost:3000/bank-accounts
Content-Type: application/json

{
  "account_number": "1111-1",
  "owner_name": "John Doe"
}

###

GET http://localhost:3000/bank-accounts/eb6cebee-5e7d-4b5d-b766-07d94b282abf/pix-keys

###

POST http://localhost:3000/bank-accounts/eb6cebee-5e7d-4b5d-b766-07d94b282abf/pix-keys
Content-Type: application/json

{
  "kind": "email",
  "key": "user@email.com"
}
