version: '3.9'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
  
  db:
    image: postgres:14.5
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nest

